spring:
  datasource:
    jdbcUrl: http://localhost:3306/batch
    username: root
    password: batch
app:
  datasource:
    jdbcUrl: http://localhost:3306/batch
    username: root
    password: batch