spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/batch
    username: root
    password: batch
app:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/app
    username: root
    password: batch